#!/bin/sh
testo() {
for thermal in $(resetprop | awk -F '[][]' '/thermal/ {print $2}'); do
if [[ $(resetprop $thermal) == running ]]; then
while true; do
stop ${thermal/init.svc.}
done
fi
done
find /sys/devices/virtual/thermal -name temp -type f -exec chmod 000 {} +
}
testis() {
for thermal in $(resetprop | awk -F '[][]' '/thermal/ {print $2}'); do
if [[ $(resetprop $thermal) == running ]]; then
stop ${thermal/init.svc.}
fi
done
find /sys/devices/virtual/thermal -name temp -type f -exec chmod 000 {} +
}
testis
sleep 5
testo
